config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
  get 'cities/:state', to: 'application#cities'
  post "/users/login" => "users#login", as: "users_login"
  
  get "/users/log_out" => "users#log_out", as: "users_log_out"
  get "/affiliates/sign_up" => "affiliates#sign_up", as: "affiliate_sign_up"
  resources :users


  post "/shops/login" => "shops#login", as: "shops_login"
  get "/shops/logout" => "shops#logout", as: "shops_logout"
  resources :shops

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  def self.create_with_omniauth(auth_hash)
      self.new(
        provider: auth_hash["provider"],
        uid: auth_hash["uid"],
        token: auth_hash["credentials"]["token"]
      )   
      end

       def update_token(auth_hash)
         self.token = auth_hash["credentials"]["token"]
         self.save
       end
end

app/models/shop.rb
class Shop < ApplicationRecord
	include BCrypt
	has_secure_password
	
  	has_many :authentications, dependent: :destroy
  	def full_street_address
 		[address,postcode,city,state].compact.join(',')
	end

	geocoded_by :full_street_address
	after_validation :geocode
end

app/models/user.rb
class User < ApplicationRecord
	include BCrypt
	has_secure_password
	enum status: { user: 0, superadmin: 1}
  	has_many :authentications, dependent: :destroy
    
    def self.create_with_auth_and_hash(authentication, auth_hash)
      if auth_hash.provider == 'google_oauth2'
        user = self.create!(
          name: auth_hash["info"]["name"],
          email: auth_hash["info"]["email"],
          password: SecureRandom.hex(16)
        )
        user.authentications << authentication
        return user
      else auth_hash.provider == 'facebook'
        user = self.create!(
          name: auth_hash["extra"]["raw_info"]["name"],
          email: auth_hash["extra"]["raw_info"]["email"],
          password: SecureRandom.hex(16)
        )
        user.authentications << authentication
        return user
      end  
    end

    # grab fb_token to access Facebook for user data
    def fb_token
      x = self.authentications.find_by(provider: 'facebook')
      return x.token unless x.nil?
    end

    def google_token
      x = self.authentications.find_by(provider: 'google')
      return x.token unless x.nil?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by_id(session[:user_id])
    end
  end
  helper_method :current_user

  # Returns true if current_user exists, false otherwise
  def logged_in?
    !current_user.nil?
  end
  helper_method :logged_in?
  
  # a convenient method to set the session to given user's id with the `:user_id` key
  def sign_in(user)
    session[:user_id] = user.id
  end

  # clears the session by setting the value of `:user_id` key to `nil`
  def sign_out
    session[:user_id] = nil
  end

  def current_shop
    if session[:shop_id]
      @current_shop ||= Shop.find_by_id(session[:shop_id])
    end
  end
  helper_method :current_shop


  def shop_logged_in?
    !current_shop.nil?
  end
  helper_method :shop_logged_in?
  
  # a convenient method to set the session to given user's id with the `:user_id` key
  def sign_in(shop)
    session[:shop_id] = shop.id
  end

  # clears the session by setting the value of `:user_id` key to `nil`
  def sign_out
    session[:shop_id] = nil
  end


  def cities
      render json: CS.cities(params[:state], :my).to_json
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create_from_omniauth
      auth_hash = request.env["omniauth.auth"]
      authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])

      # if: previously already logged in with OAuth
      if authentication != nil
        user = authentication.user
        authentication.update_token(auth_hash)
        @next = "/", @notice = "Signed in!"
      # else: user logs in with OAuth for the first time
      elsif (user = User.find_by(email: auth_hash['info']['email'])) != nil
        authentication = Authentication.create_with_omniauth(auth_hash)
        authentication.update(user_id: user.id)
      else
        authentication = Authentication.create_with_omniauth(auth_hash)
        user = User.create_with_auth_and_hash(authentication, auth_hash)
        # you are expected to have a path that leads to a page for editing user details
        #@next = edit_user_path(user)
        @notice = "User created. Please confirm or edit details"
      end

      sign_in(user)
      redirect_to "/", :info => @notice
    end

    def url_after_destroy
        "/"
    end 
end 

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
	before_action :find_shop, only: [:show, :edit, :update]


	def new
	end

	def create
		@shop = Shop.new(shop_params)
		if @shop.save
			session[:shop_id] = @shop.id
			redirect_to "/shops/#{@shop.id}"
		else

		redirect_to "/shops/new"
		end
	end

	def update
		if current_shop.id == @shop.id
			@shop.update(shop_params)
			redirect_to "/shops/#{@shop_id}", :flash => { :success => "Details updated!"}
		else
		
		redirect_to "/shops/#{@shop_id}/edit"
		end	

	end 


	def show
		@hash = Gmaps4rails.build_markers(@shop) do |shop, marker|
		    marker.lat shop.latitude
		    marker.lng shop.longitude
		end
	end

	def login
		@shop = Shop.find_by(email: params[:session][:email])
		if @shop != nil && @shop.authenticate(params[:session][:password])
			session[:shop_id] = @shop.id

			redirect_to "/shops/#{@shop.id}"
		else
			render root_path
		end
	end

	def logout
		session.clear
		redirect_to root_path
	end 
	
	def shop_params
		params.require(:shop).permit(:shop_name, :owner_name, :email, :phone, :address, :city, :state, :postcode, :password)
	end

	def find_shop
		@shop = Shop.find_by(id: params[:id])
	end	 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	

	def new

	end 

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to "/users/#{@user.id}"
		else
			render "/users/new"
		end	
	end 

	def login
		@user = User.find_by(email: params[:session][:email])
		if @user != nil && @user.authenticate(params[:session][:password])
			session[:user_id] = @user.id

			redirect_to "/users/#{@user.id}"
		else
			render root_path
		end
	end

	def log_out
		session.clear
		redirect_to root_path
	end


	private
	def user_params
		params.require(:user).permit(:name, :password, :email, :users_avatar)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
	    case level
	        when "info" then "alert alert-info"
	        when "success" then "alert alert-success"
	        when "errors" then "alert alert-warning"
	        when "alert" then "alert alert-danger"
	    end
	end	
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
    <footer id="myFooter">
        <div class="container">
            <div class="row">
                <div class="col-sm-3 myCols">
                    <h5>Join Us</h5>
                    <ul>
                        <li><%= link_to 'Register your dobi shop', new_shop_path %></li>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
                <div class="col-sm-3 myCols">
                    <h5>About us</h5>
                    <ul>
                        <li><a href="#">Company Information</a></li>
                        <li><a href="#">Contact us</a></li>
                        <li><a href="#">Reviews</a></li>
                    </ul>
                </div>
                <div class="col-sm-3 myCols">
                    <h5>Support</h5>
                    <ul>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Help desk</a></li>
                        <li><a href="#">Forums</a></li>
                    </ul>
                </div>
                <div class="col-sm-3 myCols">
                    <h5>Legal</h5>
                    <ul>
                        <li><a href="#">Terms of Service</a></li>
                        <li><a href="#">Terms of Use</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="social-networks">
            <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
            <a href="#" class="facebook"><i class="fa fa-facebook-official"></i></a>
            <a href="#" class="google"><i class="fa fa-google-plus"></i></a>
        </div>
        <div class="footer-copyright">
            <p>© 2018 Copyright Text </p>
        </div>
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Dobi Mate</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">

        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            
            <li class="nav navbar-nav navbar-right-item"><%= link_to 'Log out', users_log_out_path, class: "modal-btn navbar-right-1" %></li>

            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
        <% elsif shop_logged_in? %>
        

        <li class="nav navbar-nav navbar-right-item"><%= link_to "#{current_shop.shop_name}", shop_path(current_shop.id), class: "modal-btn navbar-right-1" %></li>
        <li class="nav navbar-nav navbar-right-item"><%= link_to 'Log out', shops_logout_path, class: "modal-btn navbar-right-1" %></li>
         
        <% else !logged_in? && !shop_logged_in? %>
        <li class="nav navbar-nav navbar-right-item"><a class="modal-btn navbar-right-1 addpointercursor" data-toggle="modal" data-target="#shoplogInModal">Business Login</a></li>
        <li class="nav navbar-nav navbar-right-item"><a class="modal-btn navbar-right-1 addpointercursor" data-toggle="modal" data-target="#signUpModalMain">Sign Up</a></li>
        <li><a class="modal-btn navbar-right-1 addpointercursor" data-toggle="modal" data-target="#logInModal">User Login</a></li>
        <% end  %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<!-- Modal sign up main-->
<div class="modal fade" id="signUpModalMain" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      
      <div class="modal-body">
        <div class="modal-close">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-container">
          <a class="modal-btn btn btn-signup" id="facebook-text" onclick="window.location.href='/auth/facebook'">
            <svg viewBox="0 0 32 32" aria-hidden="true" focusable="false" style="height: 18px; width: 18px; display: inline; margin-right:5px; fill: currentcolor;"><path d="m8 14.41v-4.17c0-.42.35-.81.77-.81h2.52v-2.08c0-4.84 2.48-7.31 7.42-7.35 1.65 0 3.22.21 4.69.64.46.14.63.42.6.88l-.56 4.06c-.04.18-.14.35-.32.53-.21.11-.42.18-.63.14-.88-.25-1.78-.35-2.8-.35-1.4 0-1.61.28-1.61 1.73v1.8h4.52c.42 0 .81.42.81.88l-.35 4.17c0 .42-.35.71-.77.71h-4.21v16c0 .42-.35.81-.77.81h-5.21c-.42 0-.8-.39-.8-.81v-16h-2.52a.78.78 0 0 1 -.78-.78" fill-rule="evenodd"></path></svg>
            
              <span>Sign up with Facebook</span>
            
          </a>
        </div>
        <div class="modal-container">
          <a class="modal-btn btn btn-signup" id="google-text" onclick="window.location.href='/auth/google_oauth2'" >
            <svg viewBox="0 0 18 18" role="presentation" aria-hidden="true" focusable="false" style="height:18px; width: 18px; display:inline; margin-right:5px" >
              <g fill="none" fill-rule="evenodd">
                <path d="M9 3.48c1.69 0 2.83.73 3.48 1.34l2.54-2.48C13.46.89 11.43 0 9 0 5.48 0 2.44 2.02.96 4.96l2.91 2.26C4.6 5.05 6.62 3.48 9 3.48z" fill="#EA4335"></path>
                <path d="M17.64 9.2c0-.74-.06-1.28-.19-1.84H9v3.34h4.96c-.1.83-.64 2.08-1.84 2.92l2.84 2.2c1.7-1.57 2.68-3.88 2.68-6.62z" fill="#4285F4"></path>
                <path d="M3.88 10.78A5.54 5.54 0 0 1 3.58 9c0-.62.11-1.22.29-1.78L.96 4.96A9.008 9.008 0 0 0 0 9c0 1.45.35 2.82.96 4.04l2.92-2.26z" fill="#FBBC05"></path>
                <path d="M9 18c2.43 0 4.47-.8 5.96-2.18l-2.84-2.2c-.76.53-1.78.9-3.12.9-2.38 0-4.4-1.57-5.12-3.74L.97 13.04C2.45 15.98 5.48 18 9 18z" fill="#34A853"></path>
                <path d="M0 0h18v18H0V0z"></path>
               </g>
             </svg>
             
              <span>Sign up with Google</span>
              
          </a>
        </div>

        <hr class="hr-text" data-content="or">

        <div class="modal-container">
          <a class="modal-btn btn btn-signup" data-toggle="modal" data-dismiss="modal" data-target="#signUpModal">
            <svg viewBox="0 0 24 24" role="presentation" aria-hidden="true" focusable="false" style="height: 18px; width: 18px; display: inline; margin-right:5px; fill: currentcolor;">
              
              <path d="m22.5 4h-21c-.83 0-1.5.67-1.5 1.51v12.99c0 .83.67 1.5 1.5 1.5h20.99a1.5 1.5 0 0 0 1.51-1.51v-12.98c0-.84-.67-1.51-1.5-1.51zm.5 14.2-6.14-7.91 6.14-4.66v12.58zm-.83-13.2-9.69 7.36c-.26.2-.72.2-.98 0l-9.67-7.36h20.35zm-21.17.63 6.14 4.67-6.14 7.88zm.63 13.37 6.3-8.1 2.97 2.26c.62.47 1.57.47 2.19 0l2.97-2.26 6.29 8.1z" fill-rule="evenodd"></path>

            </svg>
            
              <span>Sign up with Email</span>
          </a>


            <hr class="footer-hr">
            <h4 class="modal-footer-content text-center">Already have an account? <a href="#" data-toggle="modal" data-dismiss="modal" data-target="#logInModal" class="login-text">Log In</a></h4>
          
        </div>
      </div>

    </div>
  </div>
</div>

<!-- Modal sign up -->
<div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <div class="modal-close" id="modal-header-social">
          
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
          <p>You may sign up with <%= link_to "Facebook", "/auth/facebook" %> or <%= link_to "Google", "/auth/google_oauth2" %></p>
            <hr class="hr-text" data-content="or">                
          
        <div class="modal-form">
        <%= render partial: '/users/form' %>

        </div>
      </div>
    </div>
  </div>
</div>

<!-- User log in modal -->

<div class="modal fade text-center" id="logInModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h3>Login to continue</h3>
      </div>
      
      <div class="modal-body">
          <div class="form-group ">
           
            <%= form_for :session, url: users_login_path do |form| %>
              <div class="text-field form-group">
                <%= form.text_field :email, type: 'email', placeholder: "Email Address", class: "form-control" %>
              </div>

              <div class="password-field form-group">
                <%= form.password_field :password, placeholder: "Create a Password", class: "form-control" %>
              </div>

              <div class="submit-field form-group" >
                <%= form.submit 'Log In', class: "form-control form-group-submit" %>
              </div>
              <a class="modal-btn" data-toggle="modal" data-dismiss="modal" data-target="#forgotPasswordModal">Forgot password?</a>
            <% end %>
            
            <hr class="hr-text" data-content="or continue with">
            
              <div class="social-login row text-center">    
                <div class='social-login-seperator col-md-6'>
                  <a href="/auth/facebook" class="social-login-icon">
                    <svg viewBox="0 0 32 32" aria-hidden="true" focusable="false" style="height: 18px; width: 18px; display: inline; margin-right:5px; fill: currentcolor;"><path d="m8 14.41v-4.17c0-.42.35-.81.77-.81h2.52v-2.08c0-4.84 2.48-7.31 7.42-7.35 1.65 0 3.22.21 4.69.64.46.14.63.42.6.88l-.56 4.06c-.04.18-.14.35-.32.53-.21.11-.42.18-.63.14-.88-.25-1.78-.35-2.8-.35-1.4 0-1.61.28-1.61 1.73v1.8h4.52c.42 0 .81.42.81.88l-.35 4.17c0 .42-.35.71-.77.71h-4.21v16c0 .42-.35.81-.77.81h-5.21c-.42 0-.8-.39-.8-.81v-16h-2.52a.78.78 0 0 1 -.78-.78" fill-rule="evenodd"></path></svg>


                   Facebook </a>
                </div>
                <div class='social-login-seperator col-md-6'>
                  <a href="/auth/google_oauth2" class="social-login-icon text-center">
                    <svg viewBox="0 0 18 18" role="presentation" aria-hidden="true" focusable="false" style="height:18px; width: 18px; display:inline; margin-right:5px" >
                      <g fill="none" fill-rule="evenodd">
                        <path d="M9 3.48c1.69 0 2.83.73 3.48 1.34l2.54-2.48C13.46.89 11.43 0 9 0 5.48 0 2.44 2.02.96 4.96l2.91 2.26C4.6 5.05 6.62 3.48 9 3.48z" fill="#EA4335"></path>
                        <path d="M17.64 9.2c0-.74-.06-1.28-.19-1.84H9v3.34h4.96c-.1.83-.64 2.08-1.84 2.92l2.84 2.2c1.7-1.57 2.68-3.88 2.68-6.62z" fill="#4285F4"></path>
                        <path d="M3.88 10.78A5.54 5.54 0 0 1 3.58 9c0-.62.11-1.22.29-1.78L.96 4.96A9.008 9.008 0 0 0 0 9c0 1.45.35 2.82.96 4.04l2.92-2.26z" fill="#FBBC05"></path>
                        <path d="M9 18c2.43 0 4.47-.8 5.96-2.18l-2.84-2.2c-.76.53-1.78.9-3.12.9-2.38 0-4.4-1.57-5.12-3.74L.97 13.04C2.45 15.98 5.48 18 9 18z" fill="#34A853"></path>
                        <path d="M0 0h18v18H0V0z"></path>
                       </g>
                     </svg>   


                    Google
                  </a>
                </div>
              </div> 
            
          </div>
      </div>

      <div class="modal-footer">
        <h4 class="modal-footer-content text-center">Don't have an account? <a class="modal-btn" data-toggle="modal" data-dismiss="modal" data-target="#signUpModalMain">Sign Up</a></h4>
      </div>
    </div>
  </div>
</div>

<!-- shop login modal -->

<div class="modal fade text-center" id="shoplogInModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h3>Business Login to continue</h3>
        
      </div>
      
      <div class="modal-body">
          <div class="form-group ">
           

            <%= form_for :session, url: shops_login_path do |form| %>
              <div class="text-field form-group">
                <%= form.text_field :email, type: 'email', placeholder: "Email Address", class: "form-control" %>
              </div>

              <div class="password-field form-group">
                <%= form.password_field :password, placeholder: "Create a Password", class: "form-control" %>
              </div>

              <div class="submit-field form-group" >
                <%= form.submit 'Log In', class: "form-control form-group-submit" %>
              </div>
              
            <% end %>

          </div>
      </div>
    </div>
  </div> 
</div>         

app/views/shops/edit.html.erb
<%= render partial: "/layouts/navbar" %>
<div class="form-container">

	<div>
		<h2 class="sub-title">Edit your dobi shop's details HERE</h2>
	</div>	

<%= form_for :shop, url: shop_path, method: :put do |form| %>		
<%= render partial: "/shops/form", object: form %>
<% end %>
</div>

app/views/shops/new.html.erb
<%= render partial: "/layouts/navbar" %>

<div class="form-container">

	<div>
		<h2 class="sub-title">Register your dobi shop HERE</h2>
	</div>	
<%= form_for Shop.new, url: shops_path do |form| %>
    <div class="text-field form-group">
        <%= form.text_field :shop_name, placeholder: 'Shop Name', class:"form-control form-text"%>
    </div>  

    <div class="text-field form-group">
        <%= form.text_field :owner_name, placeholder: 'Shop\'s Owner Name', class:"form-control form-text" %>
    </div>

    <div class="text-field form-group">
        <%= form.text_field :email, placeholder: 'Email' , class:"form-control form-text"%>
    </div>

    <div class="text-field form-group">
        <%= form.text_field :phone, placeholder: 'Phone' , class:"form-control form-text"%>
    </div>

    <div class="text-field form-group">
        <%= form.text_field :address, placeholder: 'Address' , class:"form-control form-text"%>
    </div>

    <div class="text-field form-group">
        <%= form.text_field :postcode, placeholder: 'Postcode', class:"form-control form-text"%>
    </div>  

	    <div class="form-group">
	      <h4><%= form.label :state %></h4>
	      <select id="states-of-country" name="shop[state]" class="form-control form-control-small">
	      <option id="no-state" value="" selected>Select Your State</option>
	      <% CS.states(:my).each do |key, value| %>
	        <option value="<%= value %>" id="<%= key %>"><%= value %></option>
	      <% end %>
	      </select>
	    </div>
	    <div class="form-group">
	      <h4><%= form.label :city %></h4>
	      <select id="cities-of-state" name="shop[city]" class="form-control form-control-small">
	        <option value="" selected>Select Your City</option>
	      </select>
	    </div>
	    <script type="text/javascript">
	          $(document).on('change', '#states-of-country', function(e) {
	            var cities_of_state, input_state, state;
	            input_state = $(this);
	            cities_of_state = $('#cities-of-state');
	            state = this.options[e.target.selectedIndex].id;
	            if (state === 'no-state') {
	              return cities_of_state.html('');
	            } else {
	              $.ajax({
	                url: '/cities/' + $(this).children(':selected').attr('id'),
	                success: function(data) {
	                  var opt;
	                  opt = '<option value="" selected>Select Your City</option>';
	                  if (data.length === 0) {
	                  } else {
	                    data.forEach(function(i) {
	                      opt += '<option value="' + i + '">' + i + '</option>';
	                    });
	                    cities_of_state.html(opt);
	                  }
	                }
	              });
	            }
	          });
	        </script>

    <div class="text-field form-group">
        <%= form.password_field :password ,placeholder: 'Password' , class:"form-control form-text"%>
    </div>

    <div class="form-group">
      <%= form.submit "Register", class: "btn-apply" %>
    </div> 

<% end %>
</div>

app/views/shops/show.html.erb
<%= render partial: "/layouts/navbar" %>

<div class="container">
	
<h2>Shop Name: <%= @shop.shop_name %></h2>

<h4><%= @shop.full_street_address %></h4>
<h4><%= @shop.phone %></h4>
<h4><%= @shop.email %></h4>

<% if current_shop.id == @shop.id %>
	<%= link_to 'Edit', edit_shop_path  %>
<% end  %>
<br>
<div style='width: 100%;'>
  	<div id="map" style='width: 100%; height: 400px;'>
  	</div>
</div>
</div>

<script type="text/javascript">
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  	markers = handler.addMarkers(<%=raw @hash.to_json %>);
  	handler.bounds.extendWith(markers);
  	handler.fitMapToBounds();
  	handler.getMap().setZoom(17);
	});
</script>

app/views/users/_form.html.erb
<%= form_for User.new, url: users_path do |form| %>
    <div class="text-field form-group col-md-6">
        <%= form.text_field :name, placeholder: 'Name', class: "form-control"%>
    </div>

    <div class="text-field form-group col-md-6">
        <%= form.text_field :email, placeholder: 'Email' , class: "form-control"%>
    </div>


    <div class="text-field form-group">
        <%= form.password_field :password ,placeholder: 'Password' , class: "form-control"%>
    </div>

    <div class="form-group">
      <%= form.submit "Create an account", class: "text-field btn-submit form-control" %>
    </div>

 <% end  %>   

app/views/users/new.html.erb
<%= form_for User.new, url: users_path do |form| %>
    <div class="text-field form-group col-md-6">
        <%= form.text_field :name, placeholder: 'Name', class: "form-control"%>
    </div>

    <div class="text-field form-group col-md-6">
        <%= form.text_field :email, placeholder: 'Email' , class: "form-control"%>
    </div>


    <div class="text-field form-group">
        <%= form.password_field :password ,placeholder: 'Password' , class: "form-control"%>
    </div>

    <div class="form-group">
      <%= form.submit "Create an account", class: "text-field btn-submit form-control" %>
    </div>

 <% end  %>   

app/views/users/show.html.erb
<%= render partial: "/layouts/navbar" %>


User profile page

previous record

expenses 

app/views/welcome/index.html.erb
<%= render partial: "/layouts/navbar" %>

Home page

booking page
shop details
washing machine weight 

<%= render partial: "/layouts/footer" %>